# Generated by Django 4.0.6 on 2022-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.TextField(blank=True, null=True)),
                ('image2', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'detect',
                'managed': False,
            },
        ),
    ]
