# Generated by Django 4.0.6 on 2022-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_detect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cctv',
            fields=[
                ('camid', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cctv',
                'managed': False,
            },
        ),
    ]
