# Generated by Django 3.1.3 on 2022-08-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
