# Generated by Django 4.0.6 on 2022-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamConnectHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cam_connect_history',
                'managed': False,
            },
        ),
    ]
