# Generated by Django 4.0.6 on 2022-07-19 08:02

import cctv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturePicture',
            fields=[
                ('cpid', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=cctv.models.user_directory_path_capture_userRequest)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'capture_picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordingVideo',
            fields=[
                ('rvid', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=cctv.models.user_directory_path_video_userRequest)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'recording_video',
                'managed': False,
            },
        ),
    ]
