# Generated by Django 4.0.6 on 2022-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_capturepicture_recordingvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camid', models.CharField(blank=True, max_length=45, null=True)),
                ('time', models.DateTimeField()),
                ('confirm', models.IntegerField()),
            ],
            options={
                'db_table': 'alarm',
                'managed': False,
            },
        ),
    ]
