# Generated by Django 4.0.2 on 2022-10-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('news_title', models.TextField(primary_key=True, serialize=False)),
                ('news_url', models.TextField()),
                ('news_content', models.TextField()),
                ('news_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
    ]
